[build]
  publish = "."  # Adjust if your site files are in a folder like "dist" or "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404